const data = {
  products:[
    {
      name:'Free Shirt',
      category:'Shirts',
      image:'/images/shirt1.jpg',
      price:70,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:20,
      description:'A popular shirt',
    },
    {
      name:'Fit Shirt',
      category:'Shirts',
      image:'/images/shirt2.jpg',
      price:80,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:20,
      description:'A popular shirt',
    },
    {
      name:'Free Shirt',
      category:'Shirts',
      image:'/images/shirt3.jpg',
      price:70,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:20,
      description:'A popular shirt',
    },
    {
      name:'Free Shirt',
      category:'Shirts',
      image:'/images/shirt4.jpg',
      price:70,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:20,
      description:'A popular shirt',
    },
    {
      name:'Free Shirt',
      category:'Shirts',
      image:'/images/shirt5.jpg',
      price:70,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:20,
      description:'A popular shirt',
    },
    {
      name:'Free Shirt',
      category:'Shirts',
      image:'/images/shirt6.jpg',
      price:70,
      brand:'Nike',
      rating:4.5,
      numReviews:10,
      countInStock:20,
      description:'A popular shirt',
    },
  ],
};
export default data;